const productConfig = {
  product1: {
    title: 'SẢN PHẨM MỚI',
    urlDetail: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
    list: [
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '1200000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
    ],
  },
  product2: {
    title: 'CAMERA  VÀ LINH KIỆN CAMERA CHÍNH HÃNG.',
    urlDetail: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
    list: [
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
    ],
  },
  product3: {
    title: 'HOT TREND -HÀNG ĐIỆN  TỬ - ĐIỆN MÁY CHÍNH HÃNG.',
    urlDetail: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
    list: [
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '1000000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '100000',
        percent: '10',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
      {
        image: 'https://phatdatbinhthoi.com.vn/thumb/220x210/2/upload/sanpham/thiet-bi-bao-trom-bao-khach-bang-hong-ngoai-kawasan-i225ds.jpg',
        title: 'THIẾT BỊ BÁO TRỘM , BÁO KHÁCH BẰNG HỒNG NGOẠI KAWASAN I225DS ( TRẮNG )',
        price: '900000',
        link: 'https://phatdatbinhthoi.com.vn/thietbibaotrombaokhachbanghongngoaikawasani225dstrang-6706.htm',
      },
    ],
  },
};

export default productConfig;
